name = "tg-stream-worker"
main = "src/index.ts"
compatibility_date = "2025-01-01"
compatibility_flags = [ "nodejs_compat" ]

[[kv_namespaces]]
binding = "SESSIONS"
id = "59a01a80869c48b6af0475bdfefcae80"

[[kv_namespaces]]
binding = "FILE_MAP"
id = "394791e23626471988f6040982393950"
