name = "tg-stream-worker"
main = "src/index.ts"
compatibility_date = "2025-01-01"
compatibility_flags = [ "nodejs_compat" ]

[[kv_namespaces]]
binding = "SESSIONS"
id = "89805f8a7b99473883b5727451910400"

[[kv_namespaces]]
binding = "FILE_MAP"
id = "b600c70086454e919fe6eac4578c8f5a"
